In [2]:
# Importamos las librerías 
import numpy as np 
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

from sklearn import tree


In [3]:
#Call the database

wd = "facebook_mock.csv"

df = pd.read_csv(wd)
df.head()

Page.total.likes    Type  Category  Post.Month  Post.Weekday  Post.Hour  \
0            139441   Photo         2          12             4          3   
1            139441  Status         2          12             3         10   
2            139441   Photo         3          12             3          3   
3            139441   Photo         2          12             2         10   
4            139441   Photo         2          12             2          3   

   Paid  LPost.Tot.Reach  LPost.Tot.Impressions  Lifetime.Engaged.Users  \
0     0             2752                   5091                     178   
1     0            10460                  19057                    1457   
2     0             2413                   4373                     177   
3     1            50128                  87991                    2211   
4     0             7244                  13594                     671   

   LPost.Consumers  LPost.Consumptions  LPost.Liked.Page.Impressions  \
0              109                 159                          3078   
1             1361                1674                         11710   
2              113                 154                          2812   
3              790                1119                         61027   
4              410                 580                          6228   

   LPost.Liked.Page.Reach  LPeople.Post.Like...Engange  comment  like  share  \
0                    1640                          119        4    79     17   
1                    6112                         1108        5   130     29   
2                    1503                          132        0    66     14   
3                   32048                         1386       58  1572    147   
4                    3200                          396       19   325     49   

   Total.Interactions  Clus_km  
0                 100        0  
1                 164        0  
2                  80        0  
3                1777        1  
4                 393        1

In [4]:
#Name of columns
list(df.columns) 

['Page.total.likes',
 'Type',
 'Category',
 'Post.Month',
 'Post.Weekday',
 'Post.Hour',
 'Paid',
 'LPost.Tot.Reach',
 'LPost.Tot.Impressions',
 'Lifetime.Engaged.Users',
 'LPost.Consumers',
 'LPost.Consumptions',
 'LPost.Liked.Page.Impressions',
 'LPost.Liked.Page.Reach',
 'LPeople.Post.Like...Engange',
 'comment',
 'like',
 'share',
 'Total.Interactions',
 'Clus_km']

In [5]:
#Quitamos la columna con el objetivo.
X = df[['Page.total.likes','Type','Category', 'Post.Month', 'Post.Weekday', 'Post.Hour', 'Paid',
        'LPost.Tot.Reach', 'LPost.Tot.Impressions', 'Lifetime.Engaged.Users', 'LPost.Consumers', 'LPost.Consumptions',
         'LPost.Liked.Page.Impressions',
         'LPost.Liked.Page.Reach',
         'LPeople.Post.Like...Engange', 'comment', 'like', 'share']].values
X[0:5]

array([[139441, 'Photo', 2, 12, 4, 3, 0, 2752, 5091, 178, 109, 159, 3078,
        1640, 119, 4, 79, 17],
       [139441, 'Status', 2, 12, 3, 10, 0, 10460, 19057, 1457, 1361,
        1674, 11710, 6112, 1108, 5, 130, 29],
       [139441, 'Photo', 3, 12, 3, 3, 0, 2413, 4373, 177, 113, 154, 2812,
        1503, 132, 0, 66, 14],
       [139441, 'Photo', 2, 12, 2, 10, 1, 50128, 87991, 2211, 790, 1119,
        61027, 32048, 1386, 58, 1572, 147],
       [139441, 'Photo', 2, 12, 2, 3, 0, 7244, 13594, 671, 410, 580,
        6228, 3200, 396, 19, 325, 49]], dtype=object)

In [18]:
data = df.drop("Clus_km", axis=1)
feature_names = data.columns
data.head()

Page.total.likes    Type  Category  Post.Month  Post.Weekday  Post.Hour  \
0            139441   Photo         2          12             4          3   
1            139441  Status         2          12             3         10   
2            139441   Photo         3          12             3          3   
3            139441   Photo         2          12             2         10   
4            139441   Photo         2          12             2          3   

   Paid  LPost.Tot.Reach  LPost.Tot.Impressions  Lifetime.Engaged.Users  \
0     0             2752                   5091                     178   
1     0            10460                  19057                    1457   
2     0             2413                   4373                     177   
3     1            50128                  87991                    2211   
4     0             7244                  13594                     671   

   LPost.Consumers  LPost.Consumptions  LPost.Liked.Page.Impressions  \
0              109                 159                          3078   
1             1361                1674                         11710   
2              113                 154                          2812   
3              790                1119                         61027   
4              410                 580                          6228   

   LPost.Liked.Page.Reach  LPeople.Post.Like...Engange  comment  like  share  \
0                    1640                          119        4    79     17   
1                    6112                         1108        5   130     29   
2                    1503                          132        0    66     14   
3                   32048                         1386       58  1572    147   
4                    3200                          396       19   325     49   

   Total.Interactions  
0                 100  
1                 164  
2                  80  
3                1777  
4                 393

In [6]:
#Reescribamos la columna Type pues tupo character
from sklearn import preprocessing
le_type = preprocessing.LabelEncoder()
le_type.fit(['Photo','Status', 'Link','Video'])
X[:,1] = le_type.transform(X[:,1]) 

In [7]:
X[0:5]

array([[139441, 1, 2, 12, 4, 3, 0, 2752, 5091, 178, 109, 159, 3078, 1640,
        119, 4, 79, 17],
       [139441, 2, 2, 12, 3, 10, 0, 10460, 19057, 1457, 1361, 1674,
        11710, 6112, 1108, 5, 130, 29],
       [139441, 1, 3, 12, 3, 3, 0, 2413, 4373, 177, 113, 154, 2812, 1503,
        132, 0, 66, 14],
       [139441, 1, 2, 12, 2, 10, 1, 50128, 87991, 2211, 790, 1119, 61027,
        32048, 1386, 58, 1572, 147],
       [139441, 1, 2, 12, 2, 3, 0, 7244, 13594, 671, 410, 580, 6228,
        3200, 396, 19, 325, 49]], dtype=object)

In [8]:
#Ahora extraemos la variable objetivo
y = df["Clus_km"]
y[0:5]

0    0
1    0
2    0
3    1
4    1
Name: Clus_km, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
#test size ,  70% training, 30% test.
X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, y, test_size=0.3, random_state=3)

In [11]:
X_trainset.shape

(501, 18)

In [12]:
y_trainset.shape

(501,)

In [13]:
X_testset.shape

(215, 18)

In [14]:
y_testset.shape

(215,)

In [15]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_trainset, y_trainset)
clf.score(X_testset, y_testset)

0.9116279069767442

In [16]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_trainset, y_trainset)
rf.score(X_testset, y_testset)

0.9627906976744186

In [19]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.2294745132422757, 'like'),
 (0.22142054851915188, 'share'),
 (0.1461513366413977, 'comment'),
 (0.07774483447360543, 'LPost.Tot.Reach'),
 (0.06287730840208405, 'LPost.Liked.Page.Reach'),
 (0.05729517305637173, 'LPost.Tot.Impressions'),
 (0.05182419081200311, 'LPost.Liked.Page.Impressions'),
 (0.04629560979582368, 'Lifetime.Engaged.Users'),
 (0.03827854121341728, 'LPeople.Post.Like...Engange'),
 (0.017288655283884614, 'LPost.Consumers'),
 (0.01621504771428324, 'LPost.Consumptions'),
 (0.009647011043404635, 'Page.total.likes'),
 (0.006768625454177885, 'Category'),
 (0.00615726323421336, 'Post.Weekday'),
 (0.00511491144482348, 'Post.Hour'),
 (0.005080225353022569, 'Post.Month'),
 (0.0015371462030384074, 'Type'),
 (0.0008290581130212441, 'Paid')]

In [21]:
fbRF = RandomForestClassifier(criterion="entropy", max_depth = 4)
fbRF # muestra los parámetros dados por default 

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=4, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [22]:
fbRF.fit(X_trainset,y_trainset)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=4, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [23]:
predRF = fbRF.predict(X_testset)

In [25]:
print (predRF [0:5])
print (y_testset [0:5])

[1 1 1 1 0]
606    1
491    1
81     1
539    1
270    0
Name: Clus_km, dtype: int64


In [26]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("Random Forest's Accuracy: ", metrics.accuracy_score(y_testset, predRF))

Random Forest's Accuracy:  0.9627906976744186


In [28]:
import joblib


filename = ('FBRandomForest_model.sav')
joblib.dump(fbRF,filename)

['FBRandomForest_model.sav']