In [67]:
# Importamos las librerías 
import numpy as np 
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

from sklearn import tree


In [68]:
#Call the database

wd = "facebook_mock.csv"

df = pd.read_csv(wd)
df.head()

Page.total.likes    Type  Category  Post.Month  Post.Weekday  Post.Hour  \
0            139441   Photo         2          12             4          3   
1            139441  Status         2          12             3         10   
2            139441   Photo         3          12             3          3   
3            139441   Photo         2          12             2         10   
4            139441   Photo         2          12             2          3   

   Paid  LPost.Tot.Reach  LPost.Tot.Impressions  Lifetime.Engaged.Users  \
0     0             2752                   5091                     178   
1     0            10460                  19057                    1457   
2     0             2413                   4373                     177   
3     1            50128                  87991                    2211   
4     0             7244                  13594                     671   

   LPost.Consumers  LPost.Consumptions  LPost.Liked.Page.Impressions  \
0              109                 159                          3078   
1             1361                1674                         11710   
2              113                 154                          2812   
3              790                1119                         61027   
4              410                 580                          6228   

   LPost.Liked.Page.Reach  LPeople.Post.Like...Engange  comment  like  share  \
0                    1640                          119        4    79     17   
1                    6112                         1108        5   130     29   
2                    1503                          132        0    66     14   
3                   32048                         1386       58  1572    147   
4                    3200                          396       19   325     49   

   Total.Interactions  Clus_km  
0                 100        0  
1                 164        0  
2                  80        0  
3                1777        1  
4                 393        1

In [69]:
#Name of columns
list(df.columns) 

['Page.total.likes',
 'Type',
 'Category',
 'Post.Month',
 'Post.Weekday',
 'Post.Hour',
 'Paid',
 'LPost.Tot.Reach',
 'LPost.Tot.Impressions',
 'Lifetime.Engaged.Users',
 'LPost.Consumers',
 'LPost.Consumptions',
 'LPost.Liked.Page.Impressions',
 'LPost.Liked.Page.Reach',
 'LPeople.Post.Like...Engange',
 'comment',
 'like',
 'share',
 'Total.Interactions',
 'Clus_km']

In [70]:
#Quitamos la columna con el objetivo.
X = df[['Page.total.likes','Type','Category', 'Post.Month', 'Post.Weekday', 'Post.Hour', 'Paid','LPost.Tot.Reach']].values
X[0:5]

array([[139441, 'Photo', 2, 12, 4, 3, 0, 2752],
       [139441, 'Status', 2, 12, 3, 10, 0, 10460],
       [139441, 'Photo', 3, 12, 3, 3, 0, 2413],
       [139441, 'Photo', 2, 12, 2, 10, 1, 50128],
       [139441, 'Photo', 2, 12, 2, 3, 0, 7244]], dtype=object)

In [71]:
data = df.drop("Clus_km", axis=1)
feature_names = data.columns
data.head()

Page.total.likes    Type  Category  Post.Month  Post.Weekday  Post.Hour  \
0            139441   Photo         2          12             4          3   
1            139441  Status         2          12             3         10   
2            139441   Photo         3          12             3          3   
3            139441   Photo         2          12             2         10   
4            139441   Photo         2          12             2          3   

   Paid  LPost.Tot.Reach  LPost.Tot.Impressions  Lifetime.Engaged.Users  \
0     0             2752                   5091                     178   
1     0            10460                  19057                    1457   
2     0             2413                   4373                     177   
3     1            50128                  87991                    2211   
4     0             7244                  13594                     671   

   LPost.Consumers  LPost.Consumptions  LPost.Liked.Page.Impressions  \
0              109                 159                          3078   
1             1361                1674                         11710   
2              113                 154                          2812   
3              790                1119                         61027   
4              410                 580                          6228   

   LPost.Liked.Page.Reach  LPeople.Post.Like...Engange  comment  like  share  \
0                    1640                          119        4    79     17   
1                    6112                         1108        5   130     29   
2                    1503                          132        0    66     14   
3                   32048                         1386       58  1572    147   
4                    3200                          396       19   325     49   

   Total.Interactions  
0                 100  
1                 164  
2                  80  
3                1777  
4                 393

In [72]:
#Reescribamos la columna Type pues tupo character
from sklearn import preprocessing
le_type = preprocessing.LabelEncoder()
le_type.fit(['Photo','Status', 'Link','Video'])
X[:,1] = le_type.transform(X[:,1]) 

In [73]:
X[0:5]

array([[139441, 1, 2, 12, 4, 3, 0, 2752],
       [139441, 2, 2, 12, 3, 10, 0, 10460],
       [139441, 1, 3, 12, 3, 3, 0, 2413],
       [139441, 1, 2, 12, 2, 10, 1, 50128],
       [139441, 1, 2, 12, 2, 3, 0, 7244]], dtype=object)

In [74]:
#Ahora extraemos la variable objetivo
y = df["Clus_km"]
y[0:5]

0    0
1    0
2    0
3    1
4    1
Name: Clus_km, dtype: int64

In [75]:
from sklearn.model_selection import train_test_split

In [76]:
#test size ,  70% training, 30% test.
X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, y, test_size=0.3, random_state=3)

In [77]:
X_trainset.shape

(501, 8)

In [78]:
y_trainset.shape

(501,)

In [79]:
X_testset.shape

(215, 8)

In [80]:
y_testset.shape

(215,)

In [81]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_trainset, y_trainset)
clf.score(X_testset, y_testset)

0.7953488372093023

In [82]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_trainset, y_trainset)
rf.score(X_testset, y_testset)

0.8651162790697674

In [83]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.5282513210315958, 'LPost.Tot.Reach'),
 (0.1517690934972897, 'Page.total.likes'),
 (0.08226041328348134, 'Post.Month'),
 (0.08026737086045618, 'Post.Hour'),
 (0.05414487834926765, 'Post.Weekday'),
 (0.04528793143402623, 'Category'),
 (0.036743147079802904, 'Type'),
 (0.021275844464080183, 'Paid')]

In [84]:
fbRF = RandomForestClassifier(criterion="entropy", max_depth = 4)
fbRF # muestra los parámetros dados por default 

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=4, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [85]:
fbRF.fit(X_trainset,y_trainset)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=4, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [86]:
predRF = fbRF.predict(X_testset)

In [87]:
print (predRF [0:5])
print (y_testset [0:5])

[1 1 0 1 0]
606    1
491    1
81     1
539    1
270    0
Name: Clus_km, dtype: int64


In [88]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("Random Forest's Accuracy: ", metrics.accuracy_score(y_testset, predRF))

Random Forest's Accuracy:  0.8465116279069768


In [89]:
from joblib import dump,load
dump(fbRF, 'FBRandomForest_model_vf.joblib')


['FBRandomForest_model_vf.joblib']